version: "3.9"
name: webapp

services:
  client:
    container_name: client
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        - VITE_PORT=$VITE_PORT
    ports: 
      - "${VITE_PORT}:${VITE_PORT}"